### PR TITLE
Search integration

### PR DESCRIPTION
**Pull request by hurradieweltgehtunter**
adds a searchbar and displays results

### CODE REVIEW

**Comment by mmattel** [comment]
Why is readme.md removed completely and without replacement content?
If you want to adopt/improve the look and feel you need some steps to do so and having nothing is a bad situation.
Any repro must have a readme !

**Comment by tboerger** [comment]
@mmattel if you care so much about it you would see that there is still a readme with real content. And the commit Nähe says remove unused readme. ;)

**Comment by mmattel** [comment]
@tboerger, a readme is per design a place to describe what a repro is about and if there is more to be added like prerequisites, installation ect this can be added on either the same or another linked place. It is not a description for those who are deep in the topic but for all the other readers. The content is thererfore not for your satisfaction but for all the others. As a matter of professionalism and courtesy to the crowd, a readme with proper content is neccesary and mandatory. It is totally ok if you do not feel comfortable with the current content, but then please file the PR in that way where you add your point of view but not deleting the file and say the rest is upon others.

**Comment by tboerger** [comment]
I don't need any description what a readme is used for. As said before just check the repo, there you can see readme in adoc format AND range in md. So it's useless in all cases, not only to me.

**Comment by mmattel** [comment]
I excuse, readme.md is not affected, readme.adoc is deleted. Sorry for the confusion.

**Comment by tboerger** [comment]
Screen Recording 2019-03-20 at 11 41 AM

**Pull request merged**
