### PR TITLE
Added styles for sidebar and edited sticky function

### PR DESCRIPTION
**Pull request by LukasHirt**
## Description
Added styles to the sidebar to enable scrolling in the menu and to divide menu and versions menu. Also added a change of height of sidebar when footer is visible.

### CODE REVIEW

**Comment by mmattel** [comment]
@LukasHirt you may need to add a reviewer, else no one will see, review and approve it

**Comment by LukasHirt** [comment]
> @LukasHirt you may need to add a reviewer, else no one will see, review and approve it

Yes, I wrote to @settermjd if I should request a review from him because so far I discussed docs-ui with him. Or if you know who should I be addressing with it, just let me know.

**Comment by mmattel** [comment]
Your approach is fine, add him formal to the revierwers, this is ok to do so :smile:

**Comment by settermjd** [comment]
@LukasHirt, after reviewing the changes, on the whole, I'm really keen on them. However, two things stand out for me. 

Firstly, the new navigation menu style, for me at least, is harder to use, as the arrows next to the category names have been removed. In the production version of the theme, where the arrows are present, it makes the navigation menu easier to scan and to distinguish where one section ends and the next begins. 

Secondly, the spacing between the documentation version and "Edit this Page" could be increased, to make it easier to distinguish between the two UI elements.

Bildschirmfoto 2019-04-23 um 14 00 59 (2)

**Pull request closed without merging**
