### PR TITLE
Added highlighting

### PR DESCRIPTION
**Pull request by LukasHirt**

### CODE REVIEW

**Comment by michaelstingl** [comment]
@tboerger can we deploy the new docs-ui (wip) somewhere?

**Comment by mmattel** [comment]
@LukasHirt it would be great if you could post a before / after screenshot.
Having only the css changes is challenging to understand what it is about

**Comment by tboerger** [comment]
@michaelstingl so far we don't have an example deployment for that.

**Comment by tboerger** [comment]
@settermjd looks like you got it already running within some terminal, the port is already in use.

**Pull request merged**
