### PR TITLE
@media customization for .navbar

### PR DESCRIPTION
**Pull request by ChrisEdS**
Ensures that the navbar changes earlier into the mobile mode

### CODE REVIEW

**Comment by settermjd** [comment]
Is the highlighted area meant to happen?

bildschirmfoto 2019-02-27 um 13 15 12

**Comment by ChrisEdS** [comment]
Nope. I will do some more testing. Also, the menu on the left-hand side has to appear earlier.

**Comment by tboerger** [comment]
Earlier? Why?

**Comment by settermjd** [comment]
@ChrisEdS, any further updates on this?

**Comment by ChrisEdS** [comment]
Not at the moment. I have to invest more time here.

**Comment by settermjd** [comment]
@ChrisEdS, I've just fixed the CSS bug. If you're happy with it, please let me know.

**Comment by tboerger** [comment]
Adding this fix to #34, thanks for the hint!

**Pull request closed without merging**
