### PR TITLE
Switch drone to starlark

### PR DESCRIPTION
**Pull request by LukasHirt**

### CODE REVIEW

**Comment by LukasHirt** [comment]
Hmm, I thought the reason why CI was not starting here was because of `.drone.yml` not being switched to starlark. Is there something else that needs to be done?

**Comment by LukasHirt** [comment]
Agh, now I see the issue is not with the build not being started in #231 but result not being reported. Still, would be nice to align this with other repos and use starlark...

**Comment by phil-davis** [comment]
Extra steps are running for a PR: "Upload Artifact", "Github Release", "Notify".

In the old `.drone.yml` those had:
```
    when:
      local: false
      event: [ push ]
```

In the new `.drone.star` there is:
```
    'trigger': {
      'event': [
        'push',
      ]
    },
```

**Comment by phil-davis** [comment]
I change `trigger` to `when` in a few places. 
https://docs.drone.io/pipeline/conditions/
`when` seems to be the thing that specifies which pipeline steps to run (or not)

**Review by phil-davis — APPROVED** [review]

**Comment by LukasHirt** [comment]
@phil-davis Thanks for the adjustments!

**Comment by phil-davis** [comment]
Hopefully it works!

**Comment by LukasHirt** [comment]
@phil-davis Seems that something is broken with upload step https://drone.owncloud.com/owncloud/docs-ui/707/1/8 I'll try to look into it

**Pull request merged**
