### PR TITLE
Use owncloudci/nodejs:14 in CI

### PR DESCRIPTION
**Pull request by phil-davis**
like what is done in other repos such as https://github.com/owncloud/web/blob/master/.drone.star

### CODE REVIEW

**Comment by mmattel** [comment]
In `docs` and `docs-client-desktop` (and when the others will come too), we are running.
`"image": "owncloudci/nodejs:14",`  (not 16)
This should be in sync here. The change from webhippie to nodejs is fine to me.

**Comment by phil-davis** [comment]
> In `docs` and `docs-client-desktop` (and when the others will come too), we are running.
> `"image": "owncloudci/nodejs:14",` (not 16)
> This should be in sync here. The change from webhippie to nodejs is fine to me.

In web PR https://github.com/owncloud/web/pull/5301 `nodejs` was bumped from 14 to 16 last week.

I am not familiar with the details of the `nodejs` major versions. Do we need to stay on 14 in docs* repos?

**Comment by mmattel** [comment]
Just ran following command and 16 is not LTS...
```
nvm ls-remote | grep "Latest LTS" 
         v4.9.1   (Latest LTS: Argon)
        v6.17.1   (Latest LTS: Boron)
        v8.17.0   (Latest LTS: Carbon)
       v10.24.1   (Latest LTS: Dubnium)
       v12.22.1   (Latest LTS: Erbium)
       v14.17.1   (Latest LTS: Fermium)
```
There was an issue in the past, see note in https://github.com/owncloud/docs/blob/master/docs/build-the-docs.md#node

`Important: For docs, DO NOT use a version above v10.23.0 and below v14.17.0 as it may later conflict with other dependencies especially with the yarn serve command where you will get warnings and it may not work as expected.`

The above drove me nuts because it hindered us for a long time to switch to a more recent node version. Now with the latest LTS v14.x, it is running fine again. Proposing to stay there.

**Comment by phil-davis** [comment]
@mmattel I adjusted to use `nodejs:14`

**Review by mmattel — APPROVED** [review]
👍

**Comment by phil-davis** [comment]
I checked the docs repo - that is also using `owncloudci/nodejs:14` - so we are consistent.

**Pull request merged**
